from django.urls import path
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('', views.acara, name='Acara'),
    path('tambah-berita/', views.tambah_berita, name='Tambah Berita'),
    path('berita/<int:id>', views.detail_berita, name='Detail Berita'),
    path('berita/', views.berita, name='Berita'),
    path('acara/<int:id>/biaya-tambahan', views.biaya_tambahan, name='Biaya Tambahan'),
    path('acara/<int:id>/dana/print', views.print_dana, name='Print Dana'),
    path('acara/<int:id>/biaya-tambahan/print', views.print_biaya_tambahan, name='Print Biaya Tambahan'),
    path('acara/<int:id>/peturunan/print', views.print_peturunan, name='Print Peturunan'),
    path('acara/<int:id>/tunggakan/print', views.print_tunggakan, name='Print Tunggakan'),
    path('acara/<int:id>/dana', views.dana, name='Dana'),
    path('acara/<int:id>', views.detail_acara, name='Detail Acara'),
    path('acara/', views.acara, name='Acara'),
    path('get-jumlah/<int:id>/<int:id_peturunan>', views.get_jumlah, name='Get Jumlah'),
    path('get-dana/<int:id>', views.get_dana, name='Get Dana'),
    path('get-acara/<int:id>', views.get_acara, name='Get Acara'),
    path('hapus-dana/<int:id>', views.hapus_dana, name='Hapus Dana'),
    path('hapus-acara/<int:id>', views.hapus_acara, name='Hapus Acara'),
    path('acara/<int:id>/peturunan', views.peturunan, name='Peturunan'),
    path('get-detail-peturunan/<int:id>', views.get_detail_peturunan, name='Get Detail Peturunan'),
    path('hapus-detail-peturunan/<int:id>', views.hapus_detail_peturunan, name='Hapus Detail Peturunan'),
    path('acara/<int:id>/tunggakan', views.tunggakan, name='Tunggakan'),
    path('acara/<int:id>/validasi-bayar-transfer/', views.validasi_bayar_transfer, name='Validasi Bayar Transfer'),
    path('acara/<int:id>/validasi-pengajuan/', views.validasi_pengajuan, name='Validasi Pengajuan'),
    path('validasi-transfer/<int:id>/<int:id_acara>', views.validasi_transfer, name='Validasi Transfer'),
    path('terima-pengajuan/<int:id>/<int:id_acara>', views.terima_pengajuan, name='Terima Pengajuan'),
    path('tolak-transfer/<int:id>/<int:id_acara>', views.tolak_transfer, name='Tolak Transfer'),
    path('get-pengajuan/<int:id>', views.get_pengajuan, name='Get Pengajuan'),
    path('anggota/', views.pengguna, name='Pengguna'),
    path('hapus-anggota/<int:id>', views.hapus_anggota, name='Hapus Anggota'),
    path('get-anggota/<int:id>', views.get_anggota, name='Get Anggota'),
    path('validasi-anggota/', views.validasi_pengguna, name='Validasi Pengguna'),
    path('terima-anggota/<int:id>', views.terima_anggota, name='Terima Anggota'),
    path('kas/', views.kas, name='Kas'),
    path('get-kas/<int:id>', views.get_kas, name='Get Kas'),
    path('hapus-kas/<int:id>', views.hapus_kas, name='Hapus Kas'),
    path('acara/<int:id_acara>/usulan/<int:id>', views.detail_usulan, name='Detail Usulan'),
    path('like-usulan/<int:id>/<int:id_acara>', views.like_usulan, name='Like Usulan'),
    path('dislike-usulan/<int:id>/<int:id_acara>', views.dislike_usulan, name='Dislike Usulan'),
    path('hapus-like-usulan/<int:id>/<int:id_acara>', views.hapus_like_usulan, name='Hapus Like Usulan'),
    path('hapus-dislike-usulan/<int:id>/<int:id_acara>', views.hapus_dislike_usulan, name='Hapus Dislike Usulan'),
    path('detail-like-usulan/<int:id>/<int:id_acara>', views.detail_like_usulan, name='Detail Like Usulan'),
    path('detail-dislike-usulan/<int:id>/<int:id_acara>', views.detail_dislike_usulan, name='Detail Dislike Usulan'),
    path('hapus-detail-like-usulan/<int:id>/<int:id_acara>', views.hapus_detail_like_usulan, name='Hapus Detail Like Usulan'),
    path('hapus-detail-dislike-usulan/<int:id>/<int:id_acara>', views.hapus_detail_dislike_usulan, name='Hapus Detail Dislike Usulan'),
    path('like-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.like_comment, name='Like Comment'),
    path('dislike-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.dislike_comment, name='Dislike Comment'),
    path('hapus-like-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.hapus_like_comment, name='Hapus Like Comment'),
    path('hapus-dislike-comment/<int:id_acara>/<int:id_usulan>/<int:id>', views.hapus_dislike_comment, name='Hapus Dislike Comment'),
    path('get-notifikasi/', views.get_notifikasi, name='Get Notifikasi'),
    path('baca-notifikasi/<int:id>/', views.baca_notifikasi, name='Baca Notifikasi'),
    path('pengumuman/', views.pengumuman, name="Pengumuman"),
    path('hapus-pengumuman/<int:id>', views.hapus_pengumuman, name='Hapus Pengumuman'),
    path('get-pengumuman/<int:id>', views.get_pengumuman, name='Get Pengumuman'),
    path('print-kas/', views.print_kas, name='Print Kas'),
    path('get-berita/<int:id>', views.get_berita, name='Get Berita'),
    path('hapus-berita/<int:id>', views.hapus_berita, name='Hapus Berita'),
    path('test/', views.test, name='Test'),
    path('tutorial/', views.tutorial, name='Tutorial')
]