# Generated by Django 4.0.4 on 2022-04-25 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True)),
                ('status_selesai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_ktp', models.CharField(max_length=16)),
                ('no_hp', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=False)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('tipe', models.CharField(max_length=20)),
                ('foto_ktp', models.FileField(max_length=1000, upload_to=main.models.get_upload_path_ktp)),
                ('foto_profile', models.FileField(max_length=1000, upload_to=main.models.get_upload_path_profile)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peturunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_peturunan', models.IntegerField()),
                ('jumlah_bayar_tiap_anggota', models.IntegerField(blank=True)),
                ('tambahan_bayar', models.IntegerField(blank=True, default=0)),
                ('batas_pembayaran', models.DateField()),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acara')),
            ],
        ),
        migrations.CreateModel(
            name='TambahanPeturunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('peturunan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peturunan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('jumlah', models.IntegerField()),
                ('tanggal_kirim', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('tanggal_diapprove', models.DateTimeField(default=None, null=True)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acara')),
                ('diapprove_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ApprovePengajuan', to='main.pengguna')),
                ('dikirim_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='DetailPeturunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bayar', models.IntegerField()),
                ('tanggal_bayar', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=False)),
                ('tanggal_approve', models.DateTimeField(default=None, null=True)),
                ('bukti_pembayaran', models.FileField(blank=True, max_length=1000, upload_to=main.models.get_upload_path_bukti_pembayaran)),
                ('alasan', models.TextField(blank=True, null=True)),
                ('diapprove_oleh', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approve', to='main.pengguna')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
                ('peturunan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.peturunan')),
            ],
        ),
        migrations.CreateModel(
            name='Dana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=20)),
                ('deskripsi', models.TextField()),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('struk', models.FileField(max_length=1000, upload_to=main.models.get_upload_path_struk)),
                ('acara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.acara')),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('foto', models.FileField(max_length=1000, upload_to=main.models.get_upload_path_berita)),
                ('deskripsi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna')),
            ],
        ),
        migrations.AddField(
            model_name='acara',
            name='dibuat_oleh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pengguna'),
        ),
    ]
